'use strict';
var crypto = require('crypto');
var fs = require('fs');
var dejavu = require('dejavu');
var CredentialInterface = require('../interfaces/CredentialInterface');

var KeyfileCredential = dejavu.Class.declare({
    $name: 'KeyfileCredential',
    $implements: [CredentialInterface],
    $constants: {
        PRIORITY: 50
    },
    
    __hashBuffer: null,
    
    initialize: function(fileName) {
        var data = fs.readFileSync(fileName, {encoding: 'utf8'});
        
        // Check if the given keyfile was generated by KeePass (XML)
        // or if it is just an ordinary binary file.
        var result = data.match(/<Data>(.*?)<\/Data>/);
        if(result && result[1]) {
            data = result[1];
        }
        
        this.__hashBuffer = new Buffer(data, 'base64');
    },
    
    getPriority: function() {
        return this.$static.PRIORITY
    },
    
    getFinalKey: function() {
        return this.__hashBuffer;
    },
    
    drop: function() {
        if(this.__hashBuffer) {
            this.__hashBuffer.fill(0, 0, this.__hashBuffer.length);
            this.__hashBuffer = null;
        }
    }
});

module.exports = KeyfileCredential;